#!/bin/bash

echo cd `dirname $0` && pushd `dirname $0`

git submodule update --init

(
  cd build
  rm -rf adam-f.github.com
  mkdir adam-f.github.com
  cd adam-f.github.com
  git init
  git remote add target git@github.com:adam-f/adam-f.github.com.git
)

path=build/adam-f.github.com

for file in source/*.html.haml; do 
  target=`basename $file .haml`
  echo generating $target
  ruby shaml.rb $file app >"$path/$target"
done

mkdir "$path/storyjs"
mkdir "$path/storyjs/story"
mkdir "$path/resource"

for file in ext/storyjs/story/*.js; do
  echo cp "$file" "$path/storyjs/story/"
  cp "$file" "$path/storyjs/story/"
done 

for file in ext/storyjs/lib/*.js; do
  echo cp "$file" "$path/storyjs/"
  cp "$file" "$path/storyjs/"
done 

for file in ext/storyjs/resource/*; do
  echo cp "$file" "$path/storyjs/"
  cp "$file" "$path/storyjs/"
done 

for file in source/resource/*; do
  echo cp -r "$file" "$path/"
  cp -r "$file" "$path/"
done 

(
  cd build/adam-f.github.com
  git add *
  git commit -m "$USER: commiting website on `date`"
  if [[ "$1" = "--push" ]]; then
    git push --force target master
  fi
)

if [[ "$1" = "--run" ]]; then
  ./server/run
fi

popd
