#!/bin/bash

echo cd `dirname $0` && pushd `dirname $0`

git submodule update --init

(
  cd ext/reflect && ./makedoc
)

(
  cd ext/focalmatter && make
)

(
  cd build
  rm -rf sparecycles.github.com
  mkdir sparecycles.github.com
  cd sparecycles.github.com
  git init
  git remote add target git@github.com:sparecycles/sparecycles.github.com.git
)

path=build/sparecycles.github.com

for file in source/*.html.haml; do 
  target=`basename $file .haml`
  echo generating $target
  ruby shaml.rb $file app >"$path/$target" || exit 1
done

rm -rf $path/reflect-docs/
cp -r ext/reflect/doc/reflect-docs $path/

mkdir "$path/storyjs"
mkdir "$path/storyjs/story"
mkdir "$path/resource"
mkdir "$path/solid"

for file in ext/storyjs/story/*.js; do
  echo cp "$file" "$path/storyjs/story/"
  cp "$file" "$path/storyjs/story/"
done 

for file in ext/storyjs/lib/*.js; do
  echo cp "$file" "$path/storyjs/"
  cp "$file" "$path/storyjs/"
done 

for file in ext/storyjs/resource/*; do
  echo cp "$file" "$path/storyjs/"
  cp "$file" "$path/storyjs/"
done 

for file in source/resource/*; do
  echo cp -r "$file" "$path/"
  cp -r "$file" "$path/"
done 

mkdir "$path/focalmatter"
cp ext/focalmatter/{index.{js,html},focal.js,raphael.js} $path/focalmatter

( cd ext/solid && git clean -dxf && make )
mkdir -p "$path/solid/src"
cp -r ext/solid/{index.html,lib} $path/solid
cp -r ext/solid/src/*.js $path/solid/src

(
  cd build/sparecycles.github.com
  if [[ "$1" = "--push" ]]; then
    git add *
    git commit -m "$USER: commiting website on `date`"
    git push --force target master
  fi
)

if [[ "$1" = "--run" ]]; then
  ./server/run
fi

popd
